Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Metrics/AbcSize:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 80

Metrics/MethodLength:
  Max: 120

Metrics/ClassLength:
  Max: 250

Metrics/BlockNesting:
  Max: 5
  CountBlocks: false
